import React from 'react'

import styles from './Board.module.scss';

const Board = () => {
  return (
    <section class={styles.gridContainer}>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    <div class={styles.row}>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
      <div class={styles.column}></div>
    </div>
    </section>
  )
}

export default Board;
